---
# tasks file for clasp-build
- name: Checkout clasp from repo
  git: repo={{ clasp_repo_url }}
       dest={{ clasp_src_dir }}
       version={{ clasp_version }}
       force={{ clasp_force_checkout }}
       recursive=false
  tags:
    - clasp-checkout

- name: Copy local.config
  template: src=local.config.j2 dest="{{ clasp_src_dir }}/local.config"
  tags:
    - clasp-config

- name: Make clasp
  shell: make
  args:
    chdir: "{{ clasp_src_dir }}"
  tags:
    - clasp-make
