---
# tasks file for clasp-build
- include: checkout.yml
  tags:
    - clasp-checkout

- name: Copy local.config
  template: src=local.config.j2 dest="{{ clasp_src_dir }}/local.config"

- include: make.yml
  tags:
    - clasp-make
